### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by Bronxanarchy** [mobb111/rubygen-master#4]
C:\Python36-32\rubygen>python.exe rubygen.py
  File "rubygen.py", line 109
    print  'Recovery phrase:' + str(list2)
                            ^
SyntaxError: invalid syntax

**Comment by mobb111** [comment]
use python 3.4.0

**Comment by mobb111** [comment]
newer version sucks

**Comment by Bronxanarchy** [comment]
setup 3.4.0 and problem also

C:\Python34\rubygen>python.exe rubygen.py
  File "rubygen.py", line 109
    print  'Recovery phrase:' + str(list2)
                            ^
SyntaxError: invalid syntax

**Comment by Bronxanarchy** [comment]
change the line 

    print  ('Recovery phrase:' + str(list2))

and error     print  secret_e

and change the line

**Comment by mobb111** [comment]
on my computer is working fine with python 3.4.0 64

**Comment by Bronxanarchy** [comment]
I dont know where the error, :(

**Comment by mobb111** [comment]
give me mail u will send me there more info and i can send u my new hack program

**Comment by mobb111** [comment]
ok try now i updatet code

**Comment by Bronxanarchy** [comment]
phoneix6055@gmail.com

**Comment by mobb111** [comment]
i remowed this secret_e = (base64.b64encode(hashlib.sha512(str(list2) + '$6$').digest()))
and this now should be working  print (secret_e)

**Comment by granula** [comment]
> 
> 
> give me mail u will send me there more info and i can send u my new hack program

Can you give me?

**Comment by mobb111** [comment]
ok

**Comment by mobb111** [comment]
look i will publish it tomorow with instructions becose it is a little bit complicated it is not like this 2, this program will read dictionary.txt or dictionary.lst file and u will chose how many passphrases u will use and what api it will use for balance now i got 4 api

**Comment by granula** [comment]
> 
> 
> look i will publish it tomorow with instructions becose it is a little bit complicated it is not like this 2, this program will read dictionary.txt or dictionary.lst file and u will chose how many passphrases u will use and what api it will use for balance now i got 4 api

- 
I have such a software, but it works very slowly.
- http://pix.my/XXNYSO

**Comment by mobb111** [comment]
i understand but program will generate like the other 2 do

**Comment by mobb111** [comment]
and gona create multiprocesing to

**Comment by mobb111** [comment]
here is something new https://github.com/mobb111/Anogen-master-brainwallet-generator

**Comment by mobb111** [comment]
https://github.com/mobb111/ruby-brainwalet-destroyer
