### ISSUE TITLE
SyntaxError Python34

### ISSUE THREAD

**Issue by granula** [mobb111/rubygen-master#5]
C:\rudygen>"C:\Python34\python.exe" rubygen.py
  File "rubygen.py", line 109
    print  'Recovery phrase:' + str(list2)
                            ^
SyntaxError: invalid syntax

C:\rudygen>pip install -r requirements.txt
Downloading/unpacking requests (from -r requirements.txt (line 1))
Downloading/unpacking base58 (from -r requirements.txt (line 2))
  Downloading base58-1.0.0.tar.gz
  Running setup.py (path:C:\Users\nic\AppData\Local\Temp\pip_build_nic\base58\se
tup.py) egg_info for package base58

Downloading/unpacking ecdsa (from -r requirements.txt (line 3))
Downloading/unpacking json (from -r requirements.txt (line 4))
  Could not find any downloads that satisfy the requirement json (from -r requir
ements.txt (line 4))
Cleaning up...
No distributions at all found for json (from -r requirements.txt (line 4))
Storing debug log for failure in C:\Users\nic\pip\pip.log

C:\rudygen>

**Comment by mobb111** [comment]
ok delite json from txt

**Comment by Bronxanarchy** [comment]
python.exe -m pip install base58
python.exe -m pip install ecdsa
python.exe -m pip install request

in windows

**Comment by mobb111** [comment]
yes

**Comment by granula** [comment]
C:\rubygen>"C:\Python34\python.exe" rubygen.py
  File "rubygen.py", line 109
    print  'Recovery phrase:' + str(list2)
                            ^
SyntaxError: invalid syntax

**Comment by mobb111** [comment]
try now i update the file

**Comment by granula** [comment]
> 
> 
> try now i update the file

Update not working/

C:\rubygen>"C:\Python34\python.exe" rubygen.py

  |--------- Wallet Address ---------||-------------------- Private Key -----------
Traceback (most recent call last):
  File "rubygen.py", line 218, in <module>
    Rubygen()
  File "rubygen.py", line 186, in Rubygen
    data[0] = privateKey(data[5])
  File "rubygen.py", line 114, in privateKey
    privatekey = hashlib.sha256(binascii.hexlify(str(list2))).hexdigest()
TypeError: 'str' does not support the buffer interface

**Comment by mobb111** [comment]
u need python 3.4.0

**Comment by granula** [comment]
> 
> 
> u need python 3.4.0

3.4.0 does not work either

**Comment by mobb111** [comment]
im still building it i will publish it in few days

**Comment by mobb111** [comment]
mean while try this https://github.com/mobb111/Anogen-master-brainwallet-generator

**Comment by mobb111** [comment]
granula here it is https://github.com/mobb111/ruby-brainwalet-destroyer
